<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE JMSMAPPING [<!ELEMENT JMSMAPPING (target)*>
<!ELEMENT target (id,class,method)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT class (#PCDATA)>
<!ELEMENT method (#PCDATA)>
]>
<JMSMAPPING>
	<!-- Do not Modify / IT Arch -->
	<target>
		<id>JMS_TYPE_FAXS</id>
		<class>com.clt.framework.component.fax.dao.FaxsEAIDAO</class>
		<method>receiveFaxsQueue</method>
	</target>
	<target>
		<id>JMS_TYPE_MAILS</id>
		<class>com.clt.framework.component.common.mail.MailsProxy</class>
		<method>receiveMailsQueue</method>
	</target>
	<target>
		<id>JMS_TYPE_FTPS</id>
		<class>com.clt.framework.component.ftp.servicesio.FtpsProxy</class>
		<method>receiveFtpsQueue</method>
	</target>
	<!-- For Remote Server Back End Work -->
	<target>
		<id>COM001-0002</id>
		<class>com.clt.framework.component.backend.core.WorkOnLongTxRemoteServerJMSProxy</class>
		<method>receiveWorkOnLongTx</method>
	</target>
	<!-- Do not Modify / IT Arch -->
	<!-- ===================== OPUS CNTR ===================== -->
	<target>
		<id>EDI_T_BKG_T_CNCUS_ACK</id>
		<class>com.clt.apps.opus.esm.bkg.servicesio.CustomsDeclarationProxy</class>
		<method>opusBkgTCncusAckReplyMQ</method>
	</target>
	<target>
		<id>EDI_T_BKG_T_DECUS_ACK</id>
		<class>com.clt.apps.opus.esm.bkg.servicesio.CustomsDeclarationProxy</class>
		<method>udevcomOpusBkgTEurcusAckReceiveMQ</method>
	</target>
	<target>
		<id>EDI_T_BKG_T_EU24_ACK</id>
		<class>com.clt.apps.opus.esm.bkg.servicesio.CustomsDeclarationProxy</class>
		<method>opusBkgEur24ReplyMQ</method>
	</target>
	<target>
		<id>EDI_T_BKG_T_ISRAEL_ACK</id>
		<class>com.clt.apps.opus.esm.bkg.servicesio.CustomsDeclarationProxy</class>
		<method>opusBkgEur24ReplyMQ</method>
	</target>
	<target>
		<id>EDI_T_SCG_T_DGRQST</id>
		<class>com.clt.apps.opus.vop.scg.servicesio.SpecialCargoforPartnerManagementMQProxy</class>
		<method>receiveSpecialCargoApprRqstFromPartnerLines</method>
	</target>
	<target>
		<id>EDI_T_SCG_T_DGRQST_ACK</id>
		<class>com.clt.apps.opus.vop.scg.servicesio.SpecialCargoforPartnerManagementMQProxy</class>
		<method>receiveSpecialCargoApprRqstAckFromPartnerLines</method>
	</target>
	<target>
		<id>EDI_T_VSK_T_VSLSKD</id>
		<class>com.clt.apps.opus.vop.vsk.servicesio.ActualScheduleManagementMQProxy</class>
		<method>receiveEDIToTerminal</method>
	</target>
	<target>
		<id>EDI_T_SCE_T_CLM</id>
		<class>com.clt.apps.opus.esd.sce.servicesio.EDIReceiveMQProxy</class>
		<method>createClmdata</method>
	</target>	
	<!-- ===================== OPUS CNTR ===================== -->
	<target>
		<id>EDI_T_BKG_T_CACUS_ACK</id>
		<class>com.clt.apps.opus.esm.bkg.servicesio.CustomsDeclarationProxy</class>
		<method>ubizcomOpusBkgCancusAckReceiveMQ</method>
	</target>	
	<target>
		<id>EDI_T_BKG_T_USCUS_ACK</id>
		<class>com.clt.apps.opus.esm.bkg.servicesio.CustomsDeclarationProxy</class>
		<method>ubiz2comOpusbkgAmsAckReplyMQ</method>
	</target>	
	<target>
		<id>EDI_T_BKG_T_BECUS_ACK</id>
		<class>com.clt.apps.opus.esm.bkg.servicesio.CustomsDeclarationProxy</class>
		<method>opusbkgAncsReceiveMQ</method>
	</target>	
	<target>
		<id>EDI_T_BKG_T_EUCUS_APERAK_ACK</id>
		<class>com.clt.apps.opus.esm.bkg.servicesio.CustomsDeclarationProxy</class>
		<method>udevcomOpusBkgTEurcusAckReceiveMQ</method>
	</target>	
	<target>
		<id>EDI_T_BKG_T_NLCUS_APERAK_ACK</id>
		<class>com.clt.apps.opus.esm.bkg.servicesio.CustomsDeclarationProxy</class>
		<method>opusbkgRocsReceiveMQ</method>
	</target>	
	<target>
		<id>EDI_T_BKG_T_DGCUS_APERAK_ACK</id>
		<class>com.clt.apps.opus.esm.bkg.servicesio.TerminalDocumentationProxy</class>
		<method>udevcomOpusAkgTEurDgAckReceiveMQ</method>
	</target>	
	<target>
		<id>EDI_T_SCE_T_EQMVMT</id>
		<class>com.clt.apps.opus.esd.sce.servicesio.EDIReceiveMQProxy</class>
		<method>createEDI322data</method>
	</target>	
	<target>
		<id>EDI_T_BKG_T_JPCUS_ACK</id>
		<class>com.clt.apps.opus.esm.bkg.servicesio.CustomsDeclarationProxy</class>
		<method>opusbkgNaccsReceiveMQ</method>
	</target>	
	<target>
		<id>EDI_T_CGM_T_CHSSMVMT</id>
		<class>com.clt.apps.opus.ees.cgm.servicesio.CgmChssMvmtMQProxy</class>
		<method>poolMvmtReceive</method>
	</target>	
	<target>
		<id>EDI_T_MNR_T_ESTIMATE</id>
		<class>com.clt.apps.opus.ees.mnr.servicesio.ReceiveEstimateFromCEDEXMQProxy</class>
		<method>receiveEstimateFromCEDEX</method>
	</target>	
	<target>
		<id>EDI_T_BKG_T_JP24CUS_ACK</id>
		<class>com.clt.apps.opus.esm.bkg.servicesio.CustomsDeclarationJapanMQProxy</class>
		<method>receiveEDIForJapan24HR</method>
	</target>	
	<target>
		<id>EDI_T_BKG_VENDOR_301_ACK</id>
		<class>com.clt.apps.opus.esm.bkg.servicesio.GeneralBookingConductMQProxy</class>
		<method>receiptUsaTmlEdiAck</method>
	</target>
	<target>
        <id>EDI_T_BKG_T_CACUS_SYS_ACK</id>
        <class>com.clt.apps.opus.esm.bkg.servicesio.CustomsDeclarationProxy</class>
        <method>ediErrCaReceiveMQ</method>
    </target>   
    <target>
        <id>EDI_T_BKG_T_USCUS_SYS_ACK</id>
        <class>com.clt.apps.opus.esm.bkg.servicesio.CustomsDeclarationProxy</class>
        <method>ediErrUsReceiveMQ</method>
    </target>  
    <target>
        <id>EDI_T_BKG_T_EUCUS_SYS_ACK</id>
        <class>com.clt.apps.opus.esm.bkg.servicesio.CustomsDeclarationProxy</class>
        <method>ediErrEur24ReceiveMQ</method>
    </target>
    
    <target>
	    <id>EDI_T_TRS_T_RAIL_ACK</id>
	 	<class>com.clt.apps.opus.esd.trs.servicesio.TRSInterfaceEAIProxy</class>
	 	<method>manageUSARailWoAckMQ</method>
	</target>
	<target>
	    <id>EDI_T_TRS_T_RAIL_417</id>
	 	<class>com.clt.apps.opus.esd.trs.servicesio.TRSInterfaceEAIProxy</class>
	 	<method>manageUSARail417WoAckMQ</method>
	</target>
	<target>
	    <id>EDI_T_TRS_T_JOEDI</id>
	 	<class>com.clt.apps.opus.esd.trs.servicesio.TRSInterfaceEAIProxy</class>
	 	<method>manageGblWoAckMQ</method>
	</target>
	<target>
		<id>EDI_T_BKG_T_NZCUS_ACK</id>
		<class>com.clt.apps.opus.esm.bkg.servicesio.CustomsDeclarationProxy</class>
		<method>opusbkgNzcusReceiveMQ</method>
	</target>
</JMSMAPPING> 
